ALTER TABLE users
ADD COLUMN users_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
ADD COLUMN nickname VARCHAR(30) NOT NULL,
ADD COLUMN email VARCHAR(50) NOT NULL,
ADD COLUMN birthday DATE NOT NULL;

INSERT INTO users (nickname, email, birthday)
VALUES ('keica', 'tea.vkk@gmail.com', '1997-03-25')